### ISSUE TITLE
[Enhancement]: Add JWT key handling support

### ISSUE THREAD

**Issue by NucciTheBoss** [charmed-hpc/hpc-libs#10]
We should add JWT key handling support to `SlurmManagerBase` similar to how we handle munge keys. I went back and forth on this a bit as not all the Slurm daemons support using JWT keys - munge the OG - but I don't think it would hurt us in the long run as `slurmctld`, `slurmdbd`, and `slurmrestd` support using JWT keys.

We can enable JWT key support using composition, but without inheriting from the `Service` class:

```python3
class SlurmManagerBase(Service):
    def __init__(self, service: ServiceType) -> None:
        self.munge = MungeManager()
        self.jwt = JWTManager()
        ...
```

I'm thinking that we add a `jwtctl` tool similar `mungectl`, where we can generate, set, and get keys from the command line. That way we directly manage the key in the snap package, and folks can still benefit from the tools that we are creating even if they're not using the charm or snap package.

Let me know you thoughts @jedel1043 :eyes:

**Comment by jedel1043** [comment]
I support this, moreso knowing that it's possible that slurmd will get support for jwt in the future.

**Comment by jedel1043** [comment]
Though, this also bring an interesting question about having `MungeManager` by default, since it could be possible that in the future `Munge` will be optional. Maybe this is an argument in favour of not having a `SlurmManagerBase` class, and be something more like "build your own class from composable managers". 🌮 4️⃣ 🤔
